apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rentzone-secret
  namespace: rentzone
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:011207112032:secret:rentzone-secret-VWQTta"
          objectAlias: "app-secret"